//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace govno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public decimal Id { get; set; }
        public System.DateTime AdditionalDate { get; set; }
        public string Equipment { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string ClientSurname { get; set; }
        public string ClientName { get; set; }
        public string ClientPatronymic { get; set; }
        public Nullable<decimal> EmployeeId { get; set; }
    
        public virtual Employeee Employeee { get; set; }
    }
}
